# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/models',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/models',
                'lib_path': 'models'},
  'syms': {'models.core': {'models.core.foo': ('core.html#foo', 'models/core.py')}}}
